# Generated by Django 5.0.6 on 2024-07-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('duracion', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=100)),
                ('poster_url', models.URLField()),
                ('tmdb_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
