# Generated by Django 5.0.6 on 2024-07-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_funcion_boleto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='asiento',
        ),
        migrations.AddField(
            model_name='boleto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boleto',
            name='codigo_compra',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleto',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='boleto',
            name='tipo',
            field=models.CharField(choices=[('adulto', 'Adulto'), ('niño', 'Niño')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
