# Generated by Django 5.0.6 on 2024-07-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_boleto_asiento_boleto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='codigo_compra',
            field=models.CharField(max_length=100),
        ),
    ]
