# Generated by Django 5.0.6 on 2024-07-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pelicula_promedio_votos_pelicula_total_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='promedio_votos',
            field=models.FloatField(default=0),
        ),
    ]
