# Generated by Django 5.0.6 on 2024-07-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_funcion_asientos_ocupados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
