# Generated by Django 5.0.6 on 2024-07-23 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
