# Generated by Django 5.0.6 on 2024-07-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='trailer_url',
            field=models.URLField(default=''),
        ),
    ]
